ftm_home:
    pattern: /
    defaults: { _controller: FtmblogBundle:Blog:index}

ftm_irc:
    pattern: /irc
    defaults: { _controller: FtmblogBundle:Page:irc}

ftm_mumble:
    pattern: /mumble
    defaults: { _controller: FtmblogBundle:Page:mumble}

ftm_server:
    pattern: /server
    defaults: { _controller: FtmblogBundle:Page:server}

ftm_contact:
    pattern: /contact
    defaults: {_controller: FtmblogBundle:Page:contact}

ftm_stargate:
    pattern: /stargate.{format}
    defaults: {_controller: FtmblogBundle:Page:stargate, format: html}
    requirements:
        format: html|txt

ftm_download:
    pattern: /player/download
    defaults: {_controller: FtmblogBundle:Page:download}
    
ftm_file_download:
    pattern: /player/download/{name}
    defaults: {_controller: FtmblogBundle:Page:dlFichier}