ftm_home:
    path: /
    defaults: { _controller: FtmblogBundle:Blog:index}

ftm_irc:
    path: /irc
    defaults: { _controller: FtmblogBundle:Page:irc}

ftm_mumble:
    path: /mumble
    defaults: { _controller: FtmblogBundle:Page:mumble}

ftm_server:
    path: /server
    defaults: { _controller: FtmblogBundle:Page:server}

ftm_contact:
    path: /contact
    defaults: {_controller: FtmblogBundle:Page:contact}

ftm_stargate:
    path: /stargate.{format}
    defaults: {_controller: FtmblogBundle:Page:stargate, format: html}
    requirements:
        format: html|txt

ftm_download:
    path: /player/download
    defaults: {_controller: FtmblogBundle:Page:download}
    
ftm_file_download:
    path: /player/download/{name}
    defaults: {_controller: FtmblogBundle:Page:dlFichier}

ftm_dynmap:
    path: /dynmap
    defaults: {_controller: FtmblogBundle:Page:dynmap}
    
ftm_admin_news:
    path: /admin/addnews
    defaults: {_controller: FtmblogBundle:Blog:addNews}
