security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Ftm\PlayerBundle\Entity\Player: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_PLAYER, ROLE_BETA, ROLE_CONTROLLER]
        ROLE_BETA:        ROLE_PLAYER
        ROLE_CONTROLLER:  ROLE_PLAYER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_BETA, ROLE_CONTROLLER]

    providers:
        main:
            entity: {class: Ftm\PlayerBundle\Entity\Player, property: username}
            
        in_memory:
            memory:
                users:
                    user:  { password: gfjdkslgjfkldséjgklé, roles: [ 'ROLE_PLAYER' ] }
                    admin: { password: ourson, roles: [ 'ROLE_ADMIN' ] }
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 jours en secondes
                path:     /
                domain:   ~ 
            pattern:  ^/
            anonymous: true
            provider: in_memory
            form_login: 
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /
        login:
            pattern:  ^/$
            security: false
            
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/admin, roles: ROLE_ADMIN}
        - {path: ^/admin, roles: ROLE_CONTROLLER}
        - {path: ^/player, roles: ROLE_PLAYER}
