<?php

namespace Ftm\PlayerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionRepository extends EntityRepository
{
	//inscription exists
	public function exists($pseudo)
	{
		$resultats = $this->_em->createQueryBuilder()
								  ->select('COUNT(a)')
								  ->from($this->_entityName, 'a')
								  ->where('a.pseudo=:pseudo')
								  ->setParameter('pseudo', $pseudo)
								  ->getQuery()
								  ->getSingleScalarResult();

		
		return $resultats>0?true:false;
	}
}
