<?php

namespace Ftm\PlayerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
	public function getCount()
	{
		$resultat = $this->_em->createQueryBuilder()
								  ->select('COUNT(a)')
								  ->from($this->_entityName, 'a')
								  ->getQuery()
								  ->getSingleScalarResult();

		
		return $resultat;
	}

	public function exists($pseudo, $server)
	{
		$resultats = $this->_em->createQueryBuilder()
								  ->select('COUNT(a)')
								  ->from($this->_entityName, 'a')
								  ->where('a.username=:pseudo AND a.server=:server')
								  ->setParameter('server', $server)
								  ->setParameter('pseudo', $pseudo)
								  ->getQuery()
								  ->getSingleScalarResult();

		
		return $resultats>0?true:false;
	}
	public function member($pseudo)
	{
		$resultats = $this->_em->createQueryBuilder()
								  ->select('COUNT(a)')
								  ->from($this->_entityName, 'a')
								  ->where('a.username=:pseudo')
								  ->setParameter('pseudo', $pseudo)
								  ->getQuery()
								  ->getSingleScalarResult();

		
		return $resultats>0?true:false;
	}
}
