<?php

namespace Ftm\blogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
	public function findLastNews()
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('e')
		   ->from('FtmblogBundle:News', 'e')
		   ->where('e.id > 0')
		   ->orderBy('e.id', 'DESC');

		   

		return $qb->getQuery()
			  ->getResult();

	}
}
