<?php

namespace Ftm\blogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * stargateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class stargateRepository extends EntityRepository
{
}
