ftm_server_controll:
    path:     /admin/servercontroll
    defaults: { _controller: FtmMinecraftBundle:Main:serverControll }

ftm_ajax_server_controll:
    path: /ajax/controll
    defaults: { _controller: FtmMinecraftBundle:Main:ajaxCommand}
    requirements:
        _method: POST

ftm_server_outer_controll:
    path: /server/{server}/{action}/{apikey}
    defaults: { _controller: FtmMinecraftBundle:Main:outerControll}
